version: '3.1'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gels_avoirs_db
      MYSQL_USER: your_app_user
      MYSQL_PASSWORD: your_app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: